name: SimpleHolograms
main: eu.virtusdevelops.simpleholograms.SimpleHolograms
version: "@version@"

softdepend:
  - PlaceholderAPI


commands:
  simpleholograms:
    description: "Main command"
    permission: "simpleholograms.command.main"
    aliases:
      - "sh"
      - "simpleholo"

permissions:
  simpleholograms.command.reload:
    default: op
  simpleholograms.command.addline:
    default: op
  simpleholograms.command.removeline:
    default: op
  simpleholograms.command.setline:
    default: op
  simpleholograms.command.create:
    default: op
  simpleholograms.command.movehere:
    default: op